### ISSUE TITLE
Bug: Github button on quarto page goes to github/nhsengland rather than datascience-pd-newsletter

### ISSUE THREAD

**Issue by SamHollings** [nhsengland/datascience-pd-newsletter#10]
The github button (top right) sends you to the NHS England github organisation (https://github.com/nhsengland/) rather than to this repo.

![image](https://github.com/nhsengland/datascience-pd-newsletter/assets/52575338/fb58fccf-ccfa-4414-9bfd-23cc8aee1083)

**Comment by jenniferstruthers1-nhs** [comment]
Thanks for this spot! Now fixed.
