### ISSUE TITLE
NHSE x Microsoft Hack for Health 

### ISSUE THREAD

**Issue by amaiaita** [nhsengland/datascience-pd-newsletter#29]
## Content Suggestion:

The NHS England Data Science team, as well as a range of other analysts from across the organisation, attended an AI Hackathon at Microsoft, organised by the Data Science Team together with Microsoft and Kainos, with the key stakeholders being the NHS Websites Services Team. In this article, the author shares her experiences at the event.

Last week, the long awaited Hack for Health hosted at the beautiful Story Club, in Paddington London, by Microsoft and NHSE finally happened! At the hackathon, every team had either a Kainos or Microsoft representative, as well as a range of participants from across NHS England, including a strong Data Science Team presence, with several of our team members in each group. And unlike a usual hackathon, this one had stakeholders and well defined use cases, we were all working to one common goal.

[Continue reading...](https://nhsengland.github.io/datascience/articles/2024/12/04/microsoft-hackathon/)

![image](https://github.com/user-attachments/assets/3bd76a15-a184-4cba-96e3-bb565c5d7c9c)

**Comment by jenniferstruthers1-nhs** [comment]
thank you!! Now added into december's edition
