### ISSUE TITLE
NHS RPySOC 2024 Conference (21st Nov, Birmingham)  - registration opened

### ISSUE THREAD

**Issue by SamHollings** [nhsengland/datascience-pd-newsletter#9]
### [NHS RPySOC 2024 Conference (21st Nov, Birmingham)  - registration opened](https://nhsrcommunity.com/events/nhs-r-nhs-pycom-open-source-conference-nhs-rpysoc-2024-2024-ticket-for-in-person-attendance-on-thursday-21-november-2024/){target="_blank"}
**Thursday 21st-22nd November, 9am-5pm, in-person (Birmingham) / Online**

The **NHS RPySOC 2024 conference** is open for registration now! It will be on **21st & 22nd November in Birmingham**.
This is jointed hosted by the NHS R Community and NHS.pycom, and also promotes Open Source.

* Day 1 will be a mixture of presentations, workshops and lightening talks
* Day 2 **(in-person only)** will be ‘Unconference’ with suggestions for topics being taken on day 1.

It's a great chance to show off our work, share our learning with a like minded community and learn a few things yourself, such as the state of the industry and how techniques are being applied elsewhere.

You can either attend:
* [in-person (The ICC, Hall 11, Birmingham B1 2EA](https://nhsrcommunity.com/events/nhs-r-nhs-pycom-open-source-conference-nhs-rpysoc-2024-2024-ticket-for-in-person-attendance-on-thursday-21-november-2024/)
* [online](https://nhsrcommunity.com/events/nhs-r-nhs-pycom-open-source-conference-2024-rpysoc-2024-ticket-for-virtual-attendance-on-thursday-21-november-2024/)

**Abstract submissions haven't been opened yet.**

**Comment by jenniferstruthers1-nhs** [comment]
Thanks for this! Will be published soon :)
